Repository clouddrove/helmchart, pull requests merged in 2025-08, with the labels that each got.

#70 fix: (rbac) correct namespace uniqueness validation in _helpers.tpl
  charts/rbac/templates/_helpers.tpl
Labels: bug

#71 feat:Add Checkov workflow
  .github/workflows/checkov.yaml
Labels: enhancement

#72 feat: adding helm chart for cloudflare ddns
  .github/workflows/helm-docs.yaml
  .github/workflows/helm-release.yaml
  charts/cloudflare-ddns/Chart.yaml
  charts/cloudflare-ddns/README.md
  charts/cloudflare-ddns/templates/NOTES.txt
  charts/cloudflare-ddns/templates/_helpers.tpl
  charts/cloudflare-ddns/templates/deployment.yaml
  charts/cloudflare-ddns/templates/secret.yaml
  charts/cloudflare-ddns/templates/serviceAccount.yaml
  charts/cloudflare-ddns/values.yaml
Labels: newchart
